### ISSUE TITLE
Gulp Problem on gulp file line 6

### ISSUE THREAD

**Issue by RayFoss** [k0kubun/Nocturn#16]
Can't get this to build on Fedora 23 with up to date everything. I have been able to build various other projects including the electron based YakYak.

```
gulp bower

/home/amama/git/third-party/Nocturn/gulpfile.js:6
gulp.task('bower', () => {
                    ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at execute (/usr/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:24:18)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp-cli/index.js:150:63)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:193:16)
    at module.exports (/usr/lib/node_modules/gulp-cli/node_modules/flagged-respawn/index.js:17:3)
```

**Comment by k0kubun** [comment]
What is the version of your node.js?
The gulpfile.js is written in ES6, which may not be compiled by old node.js.

My environment is:

```sh
$ node -v
v5.6.0
```

**Comment by RayFoss** [comment]
We have lift off.

I followed the steps in http://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version

now my node -v returns 
```
$ node -v
v5.10.1
```
