### ISSUE TITLE
Uncaught Exception after failed login

### ISSUE THREAD

**Issue by chrkl** [k0kubun/Nocturn#25]
I get the following exception when using invalid twitter credentials. Installed Nocturn via brew cask on Mac OS.

Uncaught Exception:
TypeError: Cannot read property 'loadURL' of null
    at /Applications/Nocturn.app/Contents/Resources/app.asar/app/utils/authentication.js:214:17
    at /Applications/Nocturn.app/Contents/Resources/app.asar/node_modules/node-twitter-api/twitter.js:34:4
    at /Applications/Nocturn.app/Contents/Resources/app.asar/node_modules/oauth/lib/oauth.js:551:7
    at passBackControl (/Applications/Nocturn.app/Contents/Resources/app.asar/node_modules/oauth/lib/oauth.js:390:11)
    at IncomingMessage.<anonymous> (/Applications/Nocturn.app/Contents/Resources/app.asar/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by k0kubun** [comment]
Fixed this issue on Nocturn v1.4.2. Could you try it?
